n1 = eval(input("Enter the first number : "))
n2 = eval(input("Enter the second number : "))
s = n1 + n2 #sum
m = n1 - n2 #difference
p = n1 * n2 #product
d = n1 / n2 #quotient
e = n1 ** n2 #exponent
r = n1 % n2 #remainder
fd = n1 // n2 #floor division
print("\nThe sum of",n1,"and",n2,"is: ",s)
print("\nThe difference of",n1,"and",n2,"is: ",m)
print("\nThe product of",n1,"and",n2,"is: ",p)
print("\nThe quotient of",n1,"and",n2,"is: ",d)
print("\nThe exponent by",n1,"and",n2,"is: ",e)
print("\nThe remainder of",n1,"and",n2,"is: ",r)
print("\nThe floor division of",n1,"and",n2,"is: ",fd)